name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main   # Change if your default branch is different

jobs:
  push-to-hf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Push to Hugging Face Space
        run: |
          git remote add hf https://user:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Noel-14/pms_server
          git push hf main --force
